package com.kyle.route66.db.model;



import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Authorities generated by hbm2java
 */
@Entity
@Table(name="authorities"
    ,catalog="route66Db"
    , uniqueConstraints = @UniqueConstraint(columnNames={"username", "authority"}) 
)
public class Authorities  implements java.io.Serializable {


     private String username;
     private String authority;
     
     private Users user;

    public Authorities() {
    }

    public Authorities(String username, String authority) {
       this.username = username;
       this.authority = authority;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="authority", nullable=false, length=50)
    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }

//    @ManyToOne( cascade = {CascadeType.DETACH} )
//    @PrimaryKeyJoinColumn
//	public Users getUser() {
//		return user;
//	}
//
//	public void setUser(Users user) {
//		this.user = user;
//	}




}


