package com.kyle.route66.db.model;
// Generated Feb 28, 2012 7:59:49 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name="event_status"
    ,catalog="route66Db"
)
public class EventStatus  implements java.io.Serializable {


     private String statusCd;
     private String description;

    public EventStatus() {
    }

    public EventStatus(String statusCd, String description) {
       this.statusCd = statusCd;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="status_cd", unique=true, nullable=false, length=2)
    public String getCode() {
        return this.statusCd;
    }
    
    public void setCode(String code) {
        this.statusCd = code;
    }

    
    @Column(name="description", nullable=false, length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

}


