package com.kyle.route66.db.model;
// Generated Feb 28, 2012 7:59:49 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name="event_type"
    ,catalog="route66Db"
)
public class EventType  implements java.io.Serializable {


     private String code;
     private String description;

    public EventType() {
    }

    public EventType(String code, String name) {
       this.code = code;
       this.description = name;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=2)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="description", nullable=false, length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


