package com.kyle.route66.db.model;
// Generated Feb 28, 2012 7:59:49 PM by Hibernate Tools 3.4.0.CR1


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name="event_article_image"
    ,catalog="route66Db"
)
public class EventArticleImage  implements java.io.Serializable {
	private Integer eventArticleImageSeqId;
	private Integer eventSeqId;
	private Integer articleImageSeqId;
	
    private Event event;
    private ArticleImage image;

    public EventArticleImage() {
    }

    public EventArticleImage(Integer eventArticleImageSeqId,
			Integer eventSeqId, Integer articleImageSeqId) {
		super();
		this.eventArticleImageSeqId = eventArticleImageSeqId;
		this.eventSeqId = eventSeqId;
		this.articleImageSeqId = articleImageSeqId;
	}

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="event_article_image_seq_id", unique=true, nullable=false)
	public Integer getEventArticleImageSeqId() {
		return eventArticleImageSeqId;
	}

	public void setEventArticleImageSeqId(Integer eventArticleImageSeqId) {
		this.eventArticleImageSeqId = eventArticleImageSeqId;
	}

	@Column(name="event_seq_id", unique=true, nullable=false)
	public Integer getEventSeqId() {
		return eventSeqId;
	}

	public void setEventSeqId(Integer eventSeqId) {
		this.eventSeqId = eventSeqId;
	}

	@Column(name="article_image_seq_id", unique=true, nullable=false)
	public Integer getArticleImageSeqId() {
		return articleImageSeqId;
	}

	public void setArticleImageSeqId(Integer articleImageSeqId) {
		this.articleImageSeqId = articleImageSeqId;
	}

	@ManyToOne(cascade = CascadeType.MERGE)
	@JoinColumn(name="event_seq_id", insertable=false, updatable=false)
	public Event getEvent() {
		return event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name="article_image_seq_id", insertable=false, updatable=false)
	public ArticleImage getImage() {
		return image;
	}

	public void setImage(ArticleImage image) {
		this.image = image;
	}
}


