package com.kyle.route66.db.model;
// Generated Feb 28, 2012 7:59:49 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name="state"
    ,catalog="route66Db"
)
public class State  implements java.io.Serializable {


     private String code;
     private String name;

    public State() {
    }

    public State(String code, String name) {
       this.code = code;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=2)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


