package com.kyle.route66.db.model;



import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="route66Db"
)
public class Users  implements java.io.Serializable {


     private String username;
     private String password;
     private int enabled;
     
     private List<Authorities> authorities;

    public Users() {
    }

    public Users(String username, String password, int enabled) {
       this.username = username;
       this.password = password;
       this.enabled = enabled;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="enabled", nullable=false)
    public int getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(int enabled) {
        this.enabled = enabled;
    }

//    @OneToMany(mappedBy="user", cascade={CascadeType.ALL})
//	public List<Authorities> getAuthorities() {
//		return authorities;
//	}
//
//	public void setAuthorities(List<Authorities> authorities) {
//		this.authorities = authorities;
//	}




}


