package com.kyle.route66.db.model;



import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * UserAccount generated by hbm2java
 */
@Entity
@Table(name="user_account"
    ,catalog="route66Db"
)
public class UserAccount  implements java.io.Serializable {


     private String username;
     private String firstName;
     private String lastName;
     private String emailAddr;
     private String streetAddr1;
     private String streetAddr2;
     private String city;
     private String state;
     private String zip;
     
     private Users user;
     private UserAccountRequest accountRequest;
     
     private List<Event> events;

    public UserAccount() {
    }

	
    public UserAccount(String username, String emailAddr) {
        this.username = username;
        this.emailAddr = emailAddr;
    }
    public UserAccount(String username, String firstName, String lastName, String emailAddr, String streetAddr1, String streetAddr2, String city, String state, String zip) {
       this.username = username;
       this.firstName = firstName;
       this.lastName = lastName;
       this.emailAddr = emailAddr;
       this.streetAddr1 = streetAddr1;
       this.streetAddr2 = streetAddr2;
       this.city = city;
       this.state = state;
       this.zip = zip;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="first_name", length=64)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=64)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email_addr", nullable=false, length=128)
    public String getEmailAddr() {
        return this.emailAddr;
    }
    
    public void setEmailAddr(String emailAddr) {
        this.emailAddr = emailAddr;
    }

    
    @Column(name="street_addr1", length=128)
    public String getStreetAddr1() {
        return this.streetAddr1;
    }
    
    public void setStreetAddr1(String streetAddr1) {
        this.streetAddr1 = streetAddr1;
    }

    
    @Column(name="street_addr2", length=128)
    public String getStreetAddr2() {
        return this.streetAddr2;
    }
    
    public void setStreetAddr2(String streetAddr2) {
        this.streetAddr2 = streetAddr2;
    }

    
    @Column(name="city", length=128)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="state", length=45)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="zip", length=45)
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    @OneToOne(cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn
	public Users getUser() {
		return user;
	}


	public void setUser(Users user) {
		this.user = user;
	}


	@OneToOne(cascade = CascadeType.ALL)
    @PrimaryKeyJoinColumn
	public UserAccountRequest getAccountRequest() {
		return accountRequest;
	}


	public void setAccountRequest(UserAccountRequest accountRequest) {
		this.accountRequest = accountRequest;
	}

	@OneToMany(cascade = CascadeType.DETACH)
	@JoinColumn(name="state_cd")
	public List<Event> getEvents() {
		return events;
	}


	public void setEvents(List<Event> events) {
		this.events = events;
	}
	
	
}


