package com.kyle.route66.db.model;

// Generated Feb 28, 2012 7:59:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name = "zipcodes", catalog = "route66Db")
public class ZipCode implements java.io.Serializable {
	private String zipCode;
	private String state;
	private String fips_region;
	private String city;
	private BigDecimal latitude;
	private BigDecimal longitude;

	public ZipCode() {
	}

	public ZipCode(String zipCode, String state, String fips_region,
			String city, BigDecimal latitude, BigDecimal longitude) {
		this.zipCode = zipCode;
		this.state = state;
		this.fips_region = fips_region;
		this.city = city;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	@Id
	@Column(name = "zipcode", unique = true, nullable = false, length = 5)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "state", nullable = false, length = 2)
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "fips_regions", nullable = false, length = 2)
	public String getFips_region() {
		return fips_region;
	}

	public void setFips_region(String fips_region) {
		this.fips_region = fips_region;
	}

	@Column(name = "city", nullable = false, length = 64)
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "latitude", nullable = false)
	public BigDecimal getLatitude() {
		return latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false)
	public BigDecimal getLongitude() {
		return longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

}
